version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: trackguard_db
    environment:
      POSTGRES_DB: trackguard_ai
      POSTGRES_USER: trackguard
      POSTGRES_PASSWORD: ${DB_PASSWORD:-trackguard_secure_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks:
      - trackguard_network
    restart: unless-stopped

  # Redis for caching and real-time data
  redis:
    image: redis:7-alpine
    container_name: trackguard_redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_secure_password}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trackguard_network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: trackguard_backend
    environment:
      - DATABASE_URL=postgresql://trackguard:${DB_PASSWORD:-trackguard_secure_password}@postgres:5432/trackguard_ai
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis_secure_password}@redis:6379/0
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key_here}
      - UPLOAD_DIR=/app/uploads
      - MODELS_DIR=/app/models
    volumes:
      - ./Backend/uploads:/app/uploads
      - ./Backend/models:/app/models
      - ./Backend/outputs:/app/outputs
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    networks:
      - trackguard_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend1
      dockerfile: Dockerfile
    container_name: trackguard_frontend
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000/ws
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - trackguard_network
    restart: unless-stopped

  # Nginx reverse proxy (optional for production)
  nginx:
    image: nginx:alpine
    container_name: trackguard_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - trackguard_network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  trackguard_network:
    driver: bridge